# Generated by Django 5.2.2 on 2025-06-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', 'deadline', 'category']},
        ),
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.CharField(choices=[('Низкий', 'Низкий'), ('Медиум (средний)', 'Медиум (средний)'), ('Высокий', 'Высокий')], default='Низкий', max_length=20),
        ),
    ]
