# Generated by Django 4.2.11 on 2025-06-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_status_task_user_alter_category_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.CharField(choices=[('Низкий', 'Низкий'), ('Средний', 'Средний'), ('Высокий', 'Высокий')], default='Низкий', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('Не выполнено', 'Не выполнено'), ('Выполнено', 'Выполнено')], default='Не выполнено', max_length=20, null=True),
        ),
    ]
